version: '3'
services:
  db:
    image: library/mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=advanon
      - MYSQL_DATABASE=advanon_development
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/advanon
    ports:
      - "3000:3000"
    depends_on:
      - db